# Generated by Django 2.1.15 on 2021-08-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mtr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
