# Generated by Django 2.1.15 on 2021-08-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20210808_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bill',
        ),
    ]
