# Generated by Django 2.1.15 on 2021-08-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
                ('transport', models.CharField(blank=True, max_length=20)),
                ('payment', models.CharField(blank=True, max_length=100)),
                ('hsn', models.CharField(blank=True, max_length=50)),
                ('gst', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.item')),
            ],
        ),
        migrations.CreateModel(
            name='formatt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
