# Generated by Django 2.1.15 on 2021-08-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_bill_formatt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order',
        ),
        migrations.AlterField(
            model_name='bill',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adduser.transport'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adduser.client'),
        ),
    ]
