# Generated by Django 2.1.15 on 2021-08-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_auto_20210810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='pid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='rate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formatt',
            name='invno',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
