# Generated by Django 2.1.15 on 2021-08-12 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_auto_20210812_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adduser.transport'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adduser.client'),
        ),
    ]
