# Generated by Django 2.1.15 on 2021-08-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0004_auto_20210719_2330'),
        ('bill', '0010_auto_20210812_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, max_length=100)),
                ('hsn', models.CharField(blank=True, max_length=50)),
                ('gst', models.CharField(blank=True, max_length=100)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adduser.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adduser.client')),
            ],
        ),
    ]
