# Generated by Django 2.1.15 on 2021-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_temp_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='box',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='mtr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='box',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mtr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='temp',
            name='tid',
            field=models.IntegerField(default=1),
        ),
    ]
