# Generated by Django 2.1.15 on 2021-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_auto_20210813_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mtr',
        ),
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
