# Generated by Django 2.1.15 on 2021-08-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_mtr'),
        ('bill', '0018_auto_20210814_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('rate', models.CharField(blank=True, max_length=100)),
                ('box', models.CharField(blank=True, max_length=100)),
                ('total', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='box',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='mtr',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
    ]
