# Generated by Django 2.1.15 on 2021-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_auto_20210814_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='hsn',
        ),
        migrations.AddField(
            model_name='item',
            name='mtr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='mtr',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
