# Generated by Django 2.1.15 on 2021-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0020_auto_20210814_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
