# Generated by Django 2.1.15 on 2021-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0021_auto_20210814_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, max_length=100),
        ),
    ]
