# Generated by Django 2.1.15 on 2021-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0003_transport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
