# Generated by Django 2.1.15 on 2021-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0004_auto_20210719_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gst',
            field=models.CharField(choices=[('I-GST', 'I-GST'), ('C-GST & S-GST', 'C-GST & S-GST')], default=None, max_length=50),
        ),
    ]
