# Generated by Django 2.1.15 on 2021-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0005_client_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gst',
            field=models.CharField(choices=[('I-GST', 'I-GST'), ('C-GST & S-GST', 'C-GST & S-GST')], default='I-GST', max_length=50),
        ),
    ]
